dataset: Yelp2018_10104811_Chron
root: ../../data
embedding_dim: 64
epochs: 200
batch_size: 4096
optimizer: adam
lr: 1.e-3
weight_decay: 1.e-2
loss_type: Softmax
num_negs: 10
weight: 1.
stepsize: 5
gamma: 0.95