dataset: AmazonBooks_10104811_Chron
root: ../../data
epochs: 100
lr: 1.e-3
batch_size: 1024
optimizer: adam
embedding_dim: 64
num_neighbors: 10
unseen_only: 'False'
num_negs: 500
neg_weight: 500
norm_weight: 1.e-3
item_weight: 0.
init_weight: 1.e-4
w1: 1.e-8
w2: 1.
w3: 1.e-8
w4: 1.