dataset: MovieLens1M_10101811_Chron
root: ../../data
lr: 1.e-3
epochs: 500
batch_size: 1024
optimizer: adam
embedding_dim: 64
num_neighbors: 10
unseen_only: False
num_negs: 200
neg_weight: 300
norm_weight: 1.e-4
item_weight: 0.
init_weight: 1.e-3
w1: 1.e-7
w2: 1.
w3: 1.e-7
w4: 1.