root: ../../data
dataset: AmazonBeauty_550_Chron
embedding_dim: 200
ratio: 10
path: ../SASRec-BPR/Beauty-200
model: SASRec

maxlen: 50
num_heads: 1
num_blocks: 2
dropout_rate: 0.2

similarity: cosine
topology: group2group
weight4htd: 1.e-3
gamma: 0.5
K: 30

epochs: 200
batch_size: 128
optimizer: adam
lr: 1.e-4
weight_decay: 1.e-4