root: ../../data
dataset: AmazonBeauty_550_Chron
embedding_dim: 200
ratio: 10
path: ../GRU4Rec/Beauty-200
model: GRU4Rec

maxlen: 50
num_gru_layers: 1
dropout_rate: 0.3

temperature: 1.
alpha: 5.
beta: 1.

epochs: 300
batch_size: 512
optimizer: adam
lr: 5.e-4
weight_decay: 1.e-6