dataset: AmazonBooks_m1
root: ../../data
epochs: 100
weight_decay: 1.e-9
lr: 1.e-3
batch_size: 512
num_negs: 1000
margin: 0.2
weight_for_negative: 250
dropout_rate: 0.1
embedding_dim: 64
unseen_only: False