dataset: AmazonCDs_10104811_Chron
root: ../../data
num_workers: 4
epochs: 100
weight_decay: 1.e-8
lr: 1.e-4
batch_size: 1024
num_negs: 1000
margin: 0.7
weight_for_negative: 100
dropout_rate: .2
unseen_only: False