dataset: AmazonElectronics_10104811_Chron
root: ../../data
epochs: 100
weight_decay: 1.e-8
lr: 1.e-4
batch_size: 256
num_negs: 500
embedding_dim: 64 # 50 in official code
margin: 0.8
weight_for_negative: 5
dropout_rate: 0.
unseen_only: False # True in official code