root: ../../data
dataset: AmazonBeauty_550_Chron
embedding_dim: 200
ratio: 10
path: ../SASRec-BPR/Beauty-200/Beauty-200/AmazonBeauty_550_Chron/0-1108145148
model: SASRec

maxlen: 50
num_heads: 1
num_blocks: 2
dropout_rate: 0.2

K: 40
L: 40
T: 10
weight4soft: 0.5
num_topks: 500

epochs: 300
batch_size: 512
optimizer: adam
lr: 5.e-3
weight_decay: 0.