root: ../../data
dataset: Diginetica_2507_Chron
num_heads: 4
num_blocks: 2
hidden_size: 100
dropout_rate: 0.4
mask_prob: 0.5
epochs: 100
batch_size: 256
optimizer: adam
beta1: 0.9
beta2: 0.999
lr: 1.e-3
weight_decay: 1.e-4