dataset: AmazonElectronics_10104811_Chron
root: ../../data
epochs: 300
lr: 1.e-3
batch_size: 2048
optimizer: adam
embedding_dim: 64
num_neighbors: 1000
unseen_only: 'False'
num_negs: 75
neg_weight: 75
norm_weight: 5.e-5
item_weight: 1.e-7
init_weight: 1.e-3
w1: 1.e-7
w2: 1.
w3: 1.e-7
w4: 1.