dataset: Gowalla_10100811_Chron
root: ../../data
lr: 1.e-4
epochs: 1000
batch_size: 512
optimizer: adam
embedding_dim: 64
num_neighbors: 10
unseen_only: 'False'
num_negs: 1500
neg_weight: 200
norm_weight: 1.e-4
item_weight: 5.
init_weight: 1.e-4
w1: 1.e-6
w2: 1.
w3: 1.e-6
w4: 1.