dataset: Yelp2018_10104811_Chron
root: ../../data
lr: 1.e-3
epochs: 100
batch_size: 1024
optimizer: adam
embedding_dim: 64
num_neighbors: 10
unseen_only: 'False'
num_negs: 800
neg_weight: 300
norm_weight: 1.e-2
item_weight: 5.
init_weight: 1.e-4
w1: 1.e-8
w2: 1.
w3: 1.e-8
w4: 1.