dataset: AmazonBooks_10104811_Chron
root: ../../data
embedding_dim: 64
layers: 2
epochs: 1000
batch_size: 8192
optimizer: adam
lr: 5.e-4
weight_decay: 1.e-8
poly_base: Monomial
scaling_factor: 1.
is_fixed: False