root: ../../data
dataset: Gowalla_m1
epochs: 50
batch_size: 256
momentum: 0.
optimizer: sgd
lr: 9.
weight_decay: 0.01
embedding_dim: 64
num_features: 90
beta: 2.
alpha: 3.
user_weight: 0.5
item_weight: 0.5
