root: ../../data
dataset: AmazonBaby_550_MMRec
embedding_dim: 64
layers: 3
epochs: 500
batch_size: 2048
optimizer: adam
lr: 1.e-3
weight_decay: 1.e-4

vfile: visual_modality.pkl
tfile: textual_modality.pkl
afile: Null