root: ../../data
dataset: AmazonGames_550_Chron
maxlen: 50
num_heads: 4
num_blocks: 2
hidden_size: 64
dropout_rate: 0.6
epochs: 200
batch_size: 256
optimizer: adam
beta1: 0.9
beta2: 0.999
lr: 1.e-3
weight_decay: 0.