root: ../../data
dataset: AmazonBeauty_550_Chron
embedding_dim: 200
ratio: 10
path: ../GRU4Rec/Beauty-200
model: GRU4Rec

maxlen: 50
num_gru_layers: 1
dropout_rate: 0.1

temperature: 2.
weight4soft: 50

epochs: 300
batch_size: 512
optimizer: adam
lr: 1.e-3
weight_decay: 0.