dataset: AmazonBooks_10104811_Chron
root: ../../data
embedding_dim: 64
layers: 2
epochs: 1000
batch_size: 8192
optimizer: adam
lr: 1.e-3
weight_decay: 1.e-8
poly_base: Jacobi
scaling_factor: 1.
alpha: 2
beta: 2.
is_fixed: False