dataset: Gowalla_10100811_Chron
root: ../../data
embedding_dim: 64
layers: 3
epochs: 1000
batch_size: 2048
optimizer: adam
lr: 1.e-4
weight_decay: 1.e-8
poly_base: Jacobi
scaling_factor: 1.
alpha: 3.
beta: .3
is_fixed: False