dataset: AmazonCDs_m1
root: ../../data
num_workers: 4
epochs: 100
weight_decay: 5.e-4
lr: 1.e-3
batch_size: 1024
num_negs: 1500
gamma: 1.
margin: 0.7
weight_for_negative: 50
net_dropout: .2
unseen_only: False