dataset: AmazonBooks_10104811_Chron
root: ../../data
num_workers: 4
epochs: 100
weight_decay: 1.e-6
lr: 5.e-4
batch_size: 1024
num_negs: 1000
gamma: 0.5
margin: 0.4
weight_for_negative: 300
net_dropout: .1
unseen_only: False