dataset: AmazonElectronics_m1
root: ../../data
num_workers: 4
epochs: 100
weight_decay: 0.05
lr: 5.e-4
batch_size: 256
num_negs: 1000
embedding_dim: 64 # 50 in official code
gamma: 0.3
margin: 0.8
weight_for_negative: 4
net_dropout: 0.
unseen_only: False # True in official code