dataset: Yelp2018_10104811_Chron
root: ../../data
num_workers: 4
epochs: 100
weight_decay: 1.e-8
lr: 1.e-4
batch_size: 512
num_negs: 1000
gamma: .5
margin: 0.9
weight_for_negative: 100
net_dropout: .1
unseen_only: False