dataset: AmazonBooks_10104811_Chron
root: ../../data
embedding_dim: 64
epochs: 200
batch_size: 8192
optimizer: adam
lr: 1.e-3
weight_decay: 1.e-2
loss_type: DNS
num_negs: 200
weight: 2
stepsize: 5
gamma: 0.95