root: ../../data
dataset: AmazonSports_550_MMRec
embedding_dim: 64
epochs: 500
batch_size: 2048
optimizer: adam
lr: 1.e-3
weight_decay: 0.

num_ui_layers: 2
num_ii_layers: 1

weight4mAdj: 0.1
weight4modality: 1.e-3
sampling_ratio: 0.1

vfile: visual_modality.pkl
tfile: textual_modality.pkl