dataset: AmazonBooks_m1
root: ../../data
num_workers: 4
embedding_dim: 64
num_negs: 500
num_neighbors: 10
neg_weight: 500
norm_weight: 1.e-4
item_weight: 2.75
w1: 1.e-8
w2: 1.
w3: 1.e-8
w4: 1.
epochs: 2000
batch_size: 1024
optimizer: adam
lr: 1.e-3