dataset: Gowalla_m1
root: ../../data
num_workers: 4
embedding_dim: 64
num_negs: 1500
num_neighbors: 10
neg_weight: 300
norm_weight: 1.e-4
item_weight: 5.e-4
w1: 1.e-6
w2: 1.
w3: 1.e-6
w4: 1.
epochs: 2000
batch_size: 512
optimizer: adam
lr: 1.e-4
seed: 2020