dataset: Gowalla_10100811_Chron
root: ../../data
path: ../MF-BPR/MF-BPR-200-Gowalla/Gowalla-5/Gowalla_10100811_Chron/0-1013124731
embedding_dim: 200
ratio: 10
epochs: 500
batch_size: 2048
optimizer: adam
lr: 1.e-4
weight_decay: 1.e-4
model: MF
similarity: cosine
topology: group2group
weight4htd: 0.001
gamma: 0.5
K: 30