dataset: Diginetica_2507_Chron
root: ../../data
epochs: 30
batch_size: 512
lr: 1.e-3
weight_decay: 1.e-8
embedding_dim: 100
num_layers: 2
beta: 0.005
lam: 0.005
eps: 0.2
K: 10
neg_pool_size: 5000
scale4sessEmbsI: 10.