root: ../../data
dataset: AmazonBeauty_550_Chron
maxlen: 50
num_heads: 2
num_blocks: 4
hidden_size: 64
hidden_act: gelu
hidden_dropout_prob: 0.5
attention_probs_dropout_prob: 0.5

epochs: 200
batch_size: 512
optimizer: adam
lr: 1.e-3
weight_decay: 0.