root: ../../data
dataset: Steam_550_Chron
maxlen: 100
num_heads: 4
num_blocks: 1
hidden_size: 64
attn_dropout_rate: 0.4
hidden_dropout_rate: 0.6
epochs: 300
batch_size: 256
optimizer: adam
beta1: 0.9
beta2: 0.999
lr: 1.e-4
weight_decay: 1.e-6
pvn_weight: 0.001
distance_metric: wasserstein