root: ../../data
dataset: AmazonOffice_550_Chron
maxlen: 50
hidden_size: 64
num_reco_neg: 40
mask_depth: 3
path_prob: 0.5
num_heads: 4
num_gcn_layers: 2
num_trm_layers: 2
mask_steps: 7
num_mask_cand: 50
eps: 0.2
attention_probs_dropout_prob: 0.3
hidden_dropout_prob: 0.2
ii_dist: 3
epochs: 20
batch_size: 256
batch_size_con: 2048
lr: 5.e-3
weight_decay: 1.e-6