root: ../../data
dataset: MovieLens1M_550_Chron
maxlen: 200
hidden_size: 64
num_reco_neg: 40
mask_depth: 3
path_prob: 0.4
num_heads: 4
num_gcn_layers: 2
num_trm_layers: 2
mask_steps: 5
num_mask_cand: 200
eps: 0.2
attention_probs_dropout_prob: 0.5
hidden_dropout_prob: 0.
ii_dist: 3
epochs: 200
batch_size: 256
batch_size_con: 2048
lr: 1.e-3
weight_decay: 1.e-8
weight4reco: 1.e-5