dataset: AmazonBooks_10104811_Chron
root: ../../data
embedding_dim: 64
layers: 2
epochs: 1000
batch_size: 8192
optimizer: adam
lr: 1.e-3
weight_decay: 1.e-4

scaling_factor: 0.1
alpha: 1.1
beta: 1
weight4mid: 0.1