dataset: Gowalla_10100811_Chron
root: ../../data
embedding_dim: 64
layers: 3
epochs: 1000
batch_size: 2048
optimizer: adam
lr: 5.e-4
weight_decay: 1.e-6

scaling_factor: 2.
alpha: 1.5
beta: 0.7
weight4mid: 0.01