root: ../../data
dataset: Steam_550_Chron
maxlen: 50
num_heads: 1
num_blocks: 2
hidden_size: 64
dropout_rate: 0.7
epochs: 200
batch_size: 512
optimizer: adam
beta1: 0.9
beta2: 0.98
lr: 1.e-4
weight_decay: 1.e-4