dataset: AmazonHome_550_Chron
root: ../../data
epochs: 200
batch_size: 512
optimizer: adam
lr: 1.e-3
weight_decay: 0.
maxlen: 5
hidden_size: 64
dropout_rate: 0.5
num_vert: 4
num_horiz: 16
num_poss: 3 
num_negs: 2