dataset: Gowalla_10100811_Chron
root: ../../data
path: ../MF-BPR/Gowalla-200
embedding_dim: 200
ratio: 10
epochs: 1000
batch_size: 2048
optimizer: adam
lr: 5.e-4
weight_decay: 1.e-6
model: MF
num_negs: 1
num_dynamic_samples: 50
dynamic_start_epoch: 10
weight_renormalize: 'False'
K: 10
alpha: 1.
lamda: 1.
mu: 0.1