dataset: Gowalla_10100811_Chron
root: ../../data
path: ../MF-BPR/MF-BPR-200-Gowalla/Gowalla-5/Gowalla_10100811_Chron/0-1013124731
embedding_dim: 200
ratio: 10
epochs: 1000
batch_size: 2048
optimizer: adam
lr: 1.e-3
weight_decay: 1.e-8
model: MF
temperature: 0.1
weight4hard: 0.01