dataset: MovieLens1M_10101811_Chron
root: ../../data
embedding_dim: 64
layers: 3
epochs: 1000
batch_size: 2048
optimizer: adam
lr: 1.e-3
weight_decay: 1.e-3
trend_type: jc # sc
trend_coeff: 1
fusion: True